### ISSUE TITLE
espacement entre <mark> et la photo 

### ISSUE THREAD

**Issue by aslen77** [Chayma27/Shadesapp#8]
https://github.com/Chayma27/Shadesapp/blob/15eadc1974e98f38313c8eb827489c8f09a7f142/index1.html#L14

essaie de regler sa avec le css bug de rapprochement

**Comment by Chayma27** [comment]
Jsp comment la résoudre pasq c'est une image flottante et à la fois aamleteha hover donc tjiny akeka

**Comment by aslen77** [comment]
enleve le alors

**Comment by Chayma27** [comment]
C Fait

**Comment by aslen77** [comment]
super
